# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c277b1b15c54d0bd285de8bcc95c31c"
name = "choco-app"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true

[app_proxy]
prefix = 'apps'
subpath = 'proxy'
url = 'https://localhost:3000/userdata/userinfo'

